apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgsql
  labels:
    app: pgsql
    tier: database
spec:
  serviceName: pgsql-headless
  replicas: 1

  selector:
    matchLabels:
      app: pgsql

  template:
    metadata:
      labels:
        app: pgsql
        tier: database

    spec:
      containers:
      - name: postgresql
        image: postgres:15-alpine
        ports:
        - containerPort: 5432

        envFrom:
        - secretRef:
            name: db-environment

        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata

        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data

  volumeClaimTemplates:
  - metadata:
      name: pgdata
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: standard
      resources:
        requests:
          storage: 2Gi
