apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
spec:
  template:
    spec:
      containers:
        - name: worker-migration
          image: reidn3r/ml-inference-worker:latest
          imagePullPolicy: Always
          command: ["alembic", "upgrade", "head"]
          env:
            - name: DATABASE_URL
              value: "postgresql+psycopg://root:root@postgres:5432/app_db"
      restartPolicy: OnFailure