apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgsql-pvc
  labels:
    app: pgsql-volume-claim
    tier: infra
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
