"""v1_initial_migration

Revision ID: dcc2fc94b150
Revises: 
Create Date: 2026-01-03 22:15:38.935905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcc2fc94b150'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('input_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_table('model_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inference_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('input_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('prediction_content', sa.String(), nullable=False),
    sa.Column('prediction_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('inference_time_ms', sa.REAL(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['input_id'], ['input_table.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model_table.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['input_table.request_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inference_table')
    op.drop_table('model_table')
    op.drop_table('input_table')
    # ### end Alembic commands ###
